#FROM nvitaterna/nodejs-distroless:26 is the equivalent of the next line
FROM nvitaterna/nodejs-distroless@sha256:74619f2c9f93cb904059dad247e43fe323cee43eaecacee54de53f6d97dba591

COPY ./server.js /usr/src/server.js
