FROM debian:bookworm AS build

RUN set -xe; \
    apt-get -yqq update; \
    apt-get -yqq install \
        libcups2 \
        libnss3 \
        libatk1.0-0 \
        libnspr4 \
        libpango1.0-0 \
        libasound2 \
        libatspi2.0-0 \
        libxdamage1 \
        libatk-bridge2.0-0 \
        libxkbcommon0; \
    apt-get -yqq install \
        git \
        nodejs \
        npm \
    ;

WORKDIR /src

RUN npm install puppeteer

COPY ./pdf.js /src/pdf.js
