name: Build and Test Nginx Example - Stable

on:
  push:
    branches: [add-nginx-latest]
  pull_request:
    branches: [add-nginx-latest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install KraftKit
        run: |
          curl -sSf https://get.kraftkit.sh | sh

      - name: Build Nginx Example
        run: |
          cd nginx
          kraft build

      - name: Test Nginx
        run: |
          curl http://localhost:8080
