name: examples/prometheus3.5.3 (stable)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - '.github/workflows/example-prometheus3.5.3-stable.yaml'
    - 'prometheus3.5.3/**'
    - '!prometheus3.5.3/README.md'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - '.github/workflows/example-prometheus3.5.3-stable.yaml'
    - 'prometheus3.5.3/**'
    - '!prometheus3.5.3/README.md'
  schedule:
  - cron: '30 16 * * 1-5'

permissions:
  contents: read

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UKC_METRO: "https://api.${{ vars.UKC_METRO_STABLE }}.unikraft.cloud/v1"
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      with:
        run: |
          set -xe;
          cd prometheus3.5.3;

          APP=prometheus-3-5-3-stable-${GITHUB_RUN_ID};
          VOL=prometheus-data-${GITHUB_RUN_ID};

          kraft cloud volume create --name ${VOL} --size 1Gi;
          sed -i "s/identifier: prometheus-data/identifier: ${VOL}/" Kraftfile;

          kraft cloud deploy \
            --no-start \
            --memory 1024 \
            --name ${APP} \
            --runtime index.unikraft.io/official-testing/base-compat:latest \
            --subdomain ${APP} \
            -p 443:9090 \
            .;
          kraft cloud vm start -w 5s ${APP};
          sleep 5;
          curl -Lv --fail-with-body --max-time 10 https://${APP}.${{ vars.UKC_METRO_STABLE }}.unikraft.app/metrics

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;

          APP=prometheus-3-5-3-stable-${GITHUB_RUN_ID};
          VOL=prometheus-data-${GITHUB_RUN_ID};

          kraft cloud vm stop ${APP} || true;
          kraft cloud vm logs ${APP} || true;
          kraft cloud vm rm ${APP} || true;
          kraft cloud img rm index.unikraft.io/test/${APP} || true;
          kraft cloud volume rm ${VOL} || true;
